using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VesperiaSaveEditor
{
    public static class Constants
    {
        public static readonly UInt32 SAVEDATA_SIZE = 0xCCCC8;
        public static readonly UInt32 CHAR_MAX_LVL = 200;

        public static readonly string[] CharacterDlc =
        {
            "Yuri", "Estelle", "Karol", "Rita", "Raven", "Judith", "Repede"
        };

        public static readonly string[] DlcNames =
        {
            "Yuri's Bonus Title 01",
            "Yuri's Bonus Title 02",
            "Yuri's Bonus Title 03",
            "Yuri's Bonus Title 04",
            "Yuri's Bonus Title 05",
            "Yuri's Bonus Title 06",
            "Yuri's Bonus Title 07",
            "Yuri's Bonus Title 08",
            "Yuri's Bonus Title 09",
            "Yuri's Bonus Title 10",
            "Estelle's Bonus Title 01",
            "Estelle's Bonus Title 02",
            "Estelle's Bonus Title 03",
            "Estelle's Bonus Title 04",
            "Estelle's Bonus Title 05",
            "Estelle's Bonus Title 06",
            "Estelle's Bonus Title 07",
            "Estelle's Bonus Title 08",
            "Estelle's Bonus Title 09",
            "Estelle's Bonus Title 10",
            "Karol's Bonus Title 01",
            "Karol's Bonus Title 02",
            "Karol's Bonus Title 03",
            "Karol's Bonus Title 04",
            "Karol's Bonus Title 05",
            "Karol's Bonus Title 06",
            "Karol's Bonus Title 07",
            "Karol's Bonus Title 08",
            "Karol's Bonus Title 09",
            "Karol's Bonus Title 10",
            "Rita's Bonus Title 01",
            "Rita's Bonus Title 02",
            "Rita's Bonus Title 03",
            "Rita's Bonus Title 04",
            "Rita's Bonus Title 05",
            "Rita's Bonus Title 06",
            "Rita's Bonus Title 07",
            "Rita's Bonus Title 08",
            "Rita's Bonus Title 09",
            "Rita's Bonus Title 10",
            "Raven's Bonus Title 01",
            "Raven's Bonus Title 02",
            "Raven's Bonus Title 03",
            "Raven's Bonus Title 04",
            "Raven's Bonus Title 05",
            "Raven's Bonus Title 06",
            "Raven's Bonus Title 07",
            "Raven's Bonus Title 08",
            "Raven's Bonus Title 09",
            "Raven's Bonus Title 10",
            "Judith's Bonus Title 01",
            "Judith's Bonus Title 02",
            "Judith's Bonus Title 03",
            "Judith's Bonus Title 04",
            "Judith's Bonus Title 05",
            "Judith's Bonus Title 06",
            "Judith's Bonus Title 07",
            "Judith's Bonus Title 08",
            "Judith's Bonus Title 09",
            "Judith's Bonus Title 10",
            "Repede's Bonus Title 01",
            "Repede's Bonus Title 02",
            "Repede's Bonus Title 03",
            "Repede's Bonus Title 04",
            "Repede's Bonus Title 05",
            "Repede's Bonus Title 06",
            "Repede's Bonus Title 07",
            "Repede's Bonus Title 08",
            "Repede's Bonus Title 09",
            "Repede's Bonus Title 10",
            "Flynn's Bonus Title 01",
            "Flynn's Bonus Title 02",
            "Flynn's Bonus Title 03",
            "Flynn's Bonus Title 04",
            "Flynn's Bonus Title 05",
            "Flynn's Bonus Title 06",
            "Flynn's Bonus Title 07",
            "Flynn's Bonus Title 08",
            "Flynn's Bonus Title 09",
            "Flynn's Bonus Title 10",
            "Patty's Bonus Title 01",
            "Patty's Bonus Title 02",
            "Patty's Bonus Title 03",
            "Patty's Bonus Title 04",
            "Patty's Bonus Title 05",
            "Patty's Bonus Title 06",
            "Patty's Bonus Title 07",
            "Patty's Bonus Title 08",
            "Patty's Bonus Title 09",
            "Patty's Bonus Title 10",
            "300,000 Gald (1)",
            "300,000 Gald (2)",
            "300,000 Gald (3)",
            "300,000 Gald (4)",
            "10,000 Chips",
            "Lvl UP + 5 (1)",
            "Lvl UP + 5 (2)",
            "Lvl UP + 5 (3)",
            "Lvl UP + 5 (4)",
            "Lvl UP + 10 (1)",
            "Lvl UP + 10 (2)",
            "Lvl UP + 10 (3)",
            "Lvl UP + 10 (4)",
            "Free Gel Set",
            "Gel Set",
            "Herb Set",
            "Camping Kit",
            "Pack o' Useful Stuff",
            "Battle Support Item Pack",
            "Trial Synthesis Kit",
            "Synthesis Kit: Lv. 1",
            "Synthesis Kit: Lv. 2",
            "Synthesis Kit: Lv. 3",
            "Trial Skill Pack: Yuri",
            "Trial Skill Pack: Estelle",
            "Trial Skill Pack: Karol",
            "Trial Skill Pack: Rita",
            "Trial Skill Pack: Raven",
            "Trial Skill Pack: Judith",
            "Trial Skill Pack: Repede",
            "Trial Skill Pack: Flynn",
            "Trial Skill Pack: Patty",
            "Customize Pack: Yuri",
            "Customize Pack: Estelle",
            "Customize Pack: Karol",
            "Customize Pack: Rita",
            "Customize Pack: Raven",
            "Customize Pack: Judith",
            "Customize Pack: Repede",
            "Customize Pack: Flynn",
            "Customize Pack: Patty",
            "Recipe Set: HP Recovery",
            "Recipe Set: Parameter Boost",
            "Recipe Set: TP Recovery",
        };
    }
}
